db:
  image: postgres
  volumes:
    - /var/lib/postgresql
  ports:
    - "5432"
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

sonarqube:
  build: .
  links:
    - db
  ports:
    - "9000:9000"
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    - SERVICE_NAME=sonarqube